[build]
target = "x86_64-tlenek.json"

[unstable]
# must use `compiler_builtins` impls because can't link to OS C library
build-std-features = ["compiler-builtins-mem"]
# must recompile to allow custom target
build-std = ["core", "compiler_builtins"]
